# Generated by Django 3.2.24 on 2024-02-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='image',
            field=models.ImageField(default='../ik2vexictnekhozluivi', upload_to='images/'),
        ),
    ]
