# Generated by Django 3.2.24 on 2024-03-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_alter_area_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
