# Generated by Django 4.2 on 2024-05-20 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nodes", "0001_initial"),  # Adjust to your latest migration file
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS nodes_node_caused_by;"),
    ]
