# Generated by Django 4.2 on 2024-05-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_drop_nodes_node_caused_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
